version: '3.9'
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: pswd
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend
    restart: unless-stopped
    ports:
      - 5432:5432

  api-golang:
    image: golang-api-image:2.0
    build:
      context: .
      dockerfile: ./Dockerfile
      target: dev
    # init: true
    # for hot reloading in dev stage 
    volumes:
      # - type: bind
      - ./:/app/:rw
        # source: ./
        # target: /app/
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:pswd@db:5432/postgres
    ports:
      - 8080:8080
    networks:
      - backend
    restart: unless-stopped

networks:
  backend:
    # driver: bridge

volumes:
  pgdata: